# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-15 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ce',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('title', models.CharField(max_length=20)),
                ('salarytreatment', models.IntegerField()),
                ('demand', models.CharField(max_length=300)),
                ('conpanyname', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('snum', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='stu',
            fields=[
                ('stuname', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('stuage', models.IntegerField()),
                ('stusex', models.CharField(max_length=3)),
                ('stuhome', models.CharField(max_length=30)),
                ('stuschool', models.CharField(max_length=30)),
                ('stunumber', models.CharField(max_length=12)),
                ('stuyz', models.IntegerField()),
                ('stuaddress', models.CharField(max_length=30)),
                ('stugrjs', models.CharField(max_length=500)),
                ('bnum', models.CharField(max_length=300)),
            ],
        ),
    ]
